---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  roles_path: ~/chef-repo/roles
platforms:
 # - name: ubuntu-12.04
 # - name: centos-6.5
   - name: chef/centos-6.5

suites:
  - name: default
    run_list:
      - role[kitchen-icinga2]
    attributes:
